name: Generate Stage PDF

on:
  workflow_dispatch:
    inputs:
      stage_ids:
        description: "更新されたステージID (カンマ区切り)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Generate PDFs
        run: |
          IFS=',' read -ra IDS <<< "${{ github.event.inputs.stage_ids }}"
          for id in "${IDS[@]}"; do
            echo "▶️ Processing $id"
            python scripts/generate_pdf.py "$id"
          done
